
alias ls='ls --color=auto'
alias ll='ls -allh --color=auto'
alias l='ls -lAh --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias rm='rm -i'
alias grep='grep --color=auto'
alias curl='curl -s'